services:
  # 1. Backend Service (Spring Boot)
  - type: web
    name: kanban-backend
    runtime: docker
    rootDir: backend
    plan: free
    region: frankfurt
    healthCheckPath: /api/auth/login
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: kanban-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: kanban-db
          property: port
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: kanban-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: kanban-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: kanban-db
          property: database
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: JWT_SECRET_KEY
        generateValue: true

  # 2. Frontend Service (Angular)
  - type: web
    name: kanban-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist/frontend/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: kanban-db
    plan: free
    region: frankfurt
